kind: pipeline
name: default
steps:
- name: build
  image: node:6-alpine
  commands: 
  - npm install
- name: test
  image: node:6-alpine
  commands:
  - sh './jenkins/scripts/test.sh'
- name: test
  image: alpine
  commands:
  - cat README.md

