kind: pipeline
name: default
steps:
- name: build
  image: node:6-alpine
  commands: 
  - npm install
- name: test
  image: node:6-alpine
  commands:
  - sh './jenkins/scripts/test.sh'
- name: test
  image: alpine
  commands:
  - sh './jenkins/scripts/deliver.sh' 
  - input message: 'Finished using the web site? (Click "Proceed" to continue)' 
  - sh './jenkins/scripts/kill.sh' 

